language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=27
    - BUILD_TOOLS_VER=27.0.3
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$BUILD_TOOLS_VER
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository
script:
  - ./gradlew clean build
notifications:
  email: false
  slack: mad-schedule:TKW4HqsnTBL4Bmi8tlCtu0XJ
