language: android
jdk: oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=25
    - BUILD_TOOLS_VER=25.0.2
android:
  components:
    - tools
    - platform-tools
    - build-tools-$BUILD_TOOLS_VER
    - android-$ANDROID_API_LEVEL
    - extra-android-m2repository

script:
  - ./gradlew clean build
